
var oboeMonoDB = [
new OboeFingering(58, [  ], [ "x", "x", "x", "bb" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(58, [  ], [ "x", "x", "x", "bb" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(58, [  ], [ "x", "x", "x", "ab", "bb" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(58, [  ], [ "x", "x", "x", "ab", "bb" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(59, [  ], [ "x", "x", "x", "b" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(59, [  ], [ "x", "x", "x", "ab", "b" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(59, [  ], [ "x", "x", "x", "b" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(60, [  ], [ "x", "x", "x" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 0, "ppp", "fff", 349),
new OboeFingering(61, [  ], [ "x", "x", "x" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(61, [  ], [ "x", "x", "x", "eb" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(61, [  ], [ "x", "x", "x", "ab" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(62, [  ], [ "x", "x", "x" ], [ "x", "x", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(62, [  ], [ "x", "x", "x", "ab" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(62, [  ], [ "x", "x", "x", "b" ], [ "x", "x", "x" ], false, 3, 1.5, 2, "mp", "mf", false),
new OboeFingering(62.5, [  ], [ "x", "x", "x" ], [ "x", "x", "h" ], false, 3, 1.5, 0, "p", "mf", false),
new OboeFingering(62.5, [  ], [ "x", "x", "x", "b" ], [ "x", "x", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(62.5, [  ], [ "x", "x", "x", "ab" ], [ "x", "x", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(63, [  ], [ "x", "x", "x" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, 0, "ppp", "fff", 349),
new OboeFingering(63, [  ], [ "x", "x", "x", "eb" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(63, [  ], [ "x", "x", "x", "ab" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(63, [  ], [ "x", "x", "x", "bb" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(63, [  ], [ "x", "x", "x", "b" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, 1, "ppp", "fff", 348),
new OboeFingering(63, [  ], [ "x", "x", "x" ], [ "x", "x", "h", "cis" ], false, 3, 1.5, 3, "p", "mf", 11),
new OboeFingering(63.5, [  ], [ "x", "x", "x" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 0, "p", "f", false),
new OboeFingering(63.5, [  ], [ "x", "x", "x", "bb" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 1, "p", "f", false),
new OboeFingering(63.5, [  ], [ "x", "x", "x", "b" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 1, "p", "f", false),
new OboeFingering(64, [  ], [ "x", "x", "x" ], [ "x", "x", "o", "eb" ], false, 3, 1.5, -1, "mp", "ff", false),
new OboeFingering(64, [  ], [ "x", "x", "x" ], [ "x", "x", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(64, [  ], [ "x", "x", "x", "ab" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(64, [  ], [ "x", "x", "x", "bb" ], [ "x", "x", "o" ], false, 3, 1.5, 1, "p", "f", false),
new OboeFingering(64, [  ], [ "x", "x", "x", "b" ], [ "x", "x", "o" ], false, 3, 1.5, 1, "p", "f", false),
new OboeFingering(64, [  ], [ "x", "x", "x" ], [ "x", "x", "o", "cis" ], false, 3, 1.5, 1, "mp", "mf", 352),
new OboeFingering(64.5, [  ], [ "x", "x", "x" ], [ "x", "h", "o", "eb" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(64.5, [  ], [ "x", "x", "x", "bb" ], [ "x", "x", "o", "eb" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(64.5, [  ], [ "x", "x", "x" ], [ "x", "x", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(65, [  ], [ "x", "x", "x", "b", "f" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(65, [  ], [ "x", "x", "x" ], [ "x", "x", "f", "o", "eb" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(65, [  ], [ "x", "x", "x" ], [ "x", "x", "f", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(65, [  ], [ "x", "x", "x", "ab" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(65, [  ], [ "x", "x", "x", "f" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 1, "ppp", "fff", 10),
new OboeFingering(65, [  ], [ "x", "x", "x", "b" ], [ "x", "x", "f", "o", "c" ], false, 3, 1.5, 1, "p", "f", false),
new OboeFingering(65, [  ], [ "x", "x", "x" ], [ "x", "o", "x", "eb" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(65, [  ], [ "x", "x", "x", "b", "f" ], [ "x", "x", "h" ], false, 3, 1.5, 2, "pp", "f", false),
new OboeFingering(65, [  ], [ "x", "x", "x", "bb" ], [ "x", "x", "f", "o", "c" ], false, 3, 1.5, 2, "p", "f", false),
new OboeFingering(65, [  ], [ "x", "x", "x" ], [ "x", "o", "x" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(65, [  ], [ "x", "x", "x", "bb" ], [ "x", "o", "x" ], false, 3, 1.5, 2, "pp", "f", false),
new OboeFingering(65, [  ], [ "x", "x", "x" ], [ "x", "o", "x", "r" ], false, 3, 1.5, 3, "p", "mf", false),
new OboeFingering(65, [  ], [ "x", "x", "x", "bb" ], [ "x", "o", "x", "r" ], false, 3, 1.5, 3, "p", "mf", false),
new OboeFingering(65.5, [  ], [ "x", "x", "x" ], [ "x", "o", "h", "eb" ], false, 3, 1.5, 0, "ppp", "fff", 353),
new OboeFingering(65.5, [  ], [ "x", "x", "x" ], [ "x", "o", "h" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(65.5, [  ], [ "x", "x", "x", "b" ], [ "x", "o", "h" ], false, 3, 1.5, 2, "pp", "f", false),
new OboeFingering(65.5, [  ], [ "x", "x", "x" ], [ "x", "h", "f", "o", "c" ], false, 3, 1.5, 3, "p", "f", false),
new OboeFingering(66, [  ], [ "x", "x", "x" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(66, [  ], [ "x", "x", "x" ], [ "x", "f", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(66, [  ], [ "x", "x", "x", "bb" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(66, [  ], [ "x", "x", "x", "ab" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(66, [  ], [ "x", "x", "x", "b" ], [ "x", "o", "o" ], false, 3, 1.5, 1, "pp", "f", false),
new OboeFingering(66, [  ], [ "x", "x", "x" ], [ "x", "o", "o", "eb" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(66, [  ], [ "x", "x", "x", "b" ], [ "o", "x", "x", "c" ], false, 1, 1.5, 2, "pp", "pp", false),
new OboeFingering(66, [  ], [ "x", "x", "x", "bb" ], [ "o", "x", "o", "cis" ], false, 3, 1.5, 2, "mp", "mf", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x" ], [ "o", "x", "o" ], false, 3, 1.5, 0, "p", "f", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x" ], [ "o", "x", "o", "c" ], false, 3, 1.5, 1, "mp", "f", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x", "bb" ], [ "o", "x", "x", "c" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x", "b" ], [ "o", "x", "h", "c" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x" ], [ "o", "x", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x" ], [ "o", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x" ], [ "o", "x", "f", "o", "c" ], false, 3, 1.5, 2, "mp", "f", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x", "b" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 3, "p", "mf", false),
new OboeFingering(66.5, [  ], [ "x", "x", "x" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 3, "pp", "mp", 19),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", 359),
new OboeFingering(67, [  ], [ "x", "x", "x", "bb" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "o", "x", "eb" ], false, 3, 1.5, 1, "p", "f", false),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "o", "o", "c" ], false, 3, 1.5, 2, "pp", "ff", false),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "o", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67, [  ], [ "x", "x", "x" ], [ "o", "o", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67, [  ], [ "x", "x", "x", "b" ], [ "o", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67, [  ], [ "x", "x", "h", "b" ], [ "x", "o", "o" ], false, 1, 1.5, 3, "p", "mf", false),
new OboeFingering(67, [  ], [ "x", "x", "h", "b" ], [ "x", "x", "o", "c" ], false, 1, 1.5, 4, "pp", "p", 29),
new OboeFingering(67.5, [  ], [ "x", "x", "x", "b" ], [ "ab", "o", "x", "f", "o" ], false, 3, 1.5, -1, "p", "f", 358),
new OboeFingering(67.5, [  ], [ "x", "x", "x", "ab" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67.5, [  ], [ "x", "x", "x", "ab" ], [ "o", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67.5, [  ], [ "x", "x", "h" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "p", "mf", false),
new OboeFingering(67.5, [  ], [ "x", "x", "h" ], [ "o", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67.5, [  ], [ "x", "x", "h" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67.5, [  ], [ "x", "x", "h" ], [ "o", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67.5, [  ], [ "x", "x", "h", "bb" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(67.5, [  ], [ "x", "x", "h", "b" ], [ "o", "o", "x", "c" ], false, 3, 1.5, 1, "p", "mf", false),
new OboeFingering(67.5, [  ], [ "x", "x", "h", "bb" ], [ "o", "x", "h", "c" ], false, 3, 1.5, 2, "p", "mp", false),
new OboeFingering(67.5, [  ], [ "x", "x", "h" ], [ "o", "x", "o", "c" ], false, 3, 1.5, 2, "p", "mf", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", 360),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "x", "h", "cis" ], false, 3, 1.5, 1, "p", "mf", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "o", "x" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "x", "o" ], false, 3, 1.5, 2, "mp", "f", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "o", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab", "b" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(68, [  ], [ "x", "x", "x", "ab" ], [ "o", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(68, [  ], [ "x", "x", "h" ], [ "o", "x", "x", "c" ], false, 1, 1.5, 3, "pp", "mp", false),
new OboeFingering(68, [  ], [ "x", "x", "h", "bb" ], [ "o", "x", "o", "c" ], false, 3, 1.5, 3, "mp", "mf", false),
new OboeFingering(68.5, [  ], [ "x", "x", "h", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "p", "f", false),
new OboeFingering(68.5, [  ], [ "x", "x", "h", "bb" ], [ "ab", "o", "x", "x", "c" ], false, 3, 1.5, 1, "mp", "mf", false),
new OboeFingering(68.5, [  ], [ "x", "x", "h", "ab" ], [ "o", "x", "x" ], false, 3, 1.5, 1, "p", "mp", 365),
new OboeFingering(68.5, [  ], [ "x", "x", "h", "ab" ], [ "o", "x", "o" ], false, 3, 1.5, 2, "mp", "mf", false),
new OboeFingering(68.5, [  ], [ "x", "x", "o" ], [ "o", "x", "x" ], false, 3, 1.5, 3, "mp", "mp", false),
new OboeFingering(69, [  ], [ "x", "x", "o" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69, [  ], [ "x", "x", "o" ], [ "o", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69, [  ], [ "x", "x", "o" ], [ "o", "o", "o", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69, [  ], [ "x", "x", "o" ], [ "o", "x", "h", "c" ], false, 3, 1.5, 1, "pp", "f", false),
new OboeFingering(69, [  ], [ "x", "x", "o" ], [ "o", "x", "o" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(69, [  ], [ "x", "x", "o" ], [ "o", "x", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69, [  ], [ "x", "x", "o" ], [ "abtrill", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69, [  ], [ "x", "x", "o", "b" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69, [  ], [ "x", "x", "o", "bb" ], [ "o", "x", "o", "c" ], false, 3, 1.5, 2, "mp", "mf", false),
new OboeFingering(69, [  ], [ "x", "h", "x", "bb" ], [ "o", "o", "o" ], false, 4, 1.5, 3, "mf", "f", false),
new OboeFingering(69, [  ], [ "x", "o", "x", "ab" ], [ "x", "x", "h", "c" ], false, 1, 1.5, 4, "p", "p", false),
new OboeFingering(69, [  ], [ "x", "h", "x" ], [ "x", "x", "o" ], false, 1, 1.5, 5, "pp", "pp", false),
new OboeFingering(69, [  ], [ "x", "h", "x", "b" ], [ "x", "x", "f", "o", "c" ], false, 2, 1.5, 5, "pp", "pp", 71),
new OboeFingering(69, [  ], [ "x", "h", "x", "b" ], [ "x", "x", "o", "cis" ], false, 1, 1.5, 5, "pp", "pp", 72),
new OboeFingering(69.5, [  ], [ "x", "x", "o", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69.5, [  ], [ "x", "x", "o" ], [ "ab", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69.5, [  ], [ "x", "x", "o", "ab" ], [ "o", "x", "x", "c" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(69.5, [  ], [ "x", "x", "o", "ab" ], [ "o", "x", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69.5, [  ], [ "x", "x", "o", "bb" ], [ "ab", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69.5, [  ], [ "x", "x", "o" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(69.5, [  ], [ "x", "o", "h", "ab" ], [ "x", "o", "x" ], false, 3, 1.5, 2, "pp", "mp", false),
new OboeFingering(69.5, [  ], [ "x", "o", "h", "ab" ], [ "x", "o", "o" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(69.5, [  ], [ "x", "o", "h", "ab" ], [ "x", "x", "f", "o", "eb" ], false, 3, 1.5, 3, "pp", "mp", false),
new OboeFingering(69.5, [  ], [ "x", "h", "x", "bb", "f" ], [ "x", "x", "x", "eb" ], false, 1, 1.5, 4, "ppp", "pp", 57),
new OboeFingering(69.5, [  ], [ "x", "h", "x" ], [ "x", "x", "f", "o" ], false, 1, 1.5, 4, "ppp", "pp", 77),
new OboeFingering(69.5, [  ], [ "x", "h", "x", "bb", "f" ], [ "x", "o", "x" ], false, 1, 1.5, 4, "ppp", "pp", 80),
new OboeFingering(69.5, [  ], [ "x", "h", "x" ], [ "x", "o", "h" ], false, 1, 1.5, 4, "ppp", "mp", 81),
new OboeFingering(69.5, [  ], [ "x", "h", "x", "f" ], [ "x", "o", "h", "cis" ], false, 1, 1.5, 4, "ppp", "mp", 83),
new OboeFingering(69.5, [  ], [ "x", "h", "x" ], [ "x", "o", "o" ], false, 1, 1.5, 4, "ppp", "mp", 87),
new OboeFingering(69.5, [  ], [ "x", "h", "x", "b" ], [ "f", "x", "x", "x", "c" ], false, 1, 1.5, 5, "ppp", "ppp", 59),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", 366),
new OboeFingering(70, [  ], [ "x", "x", "o", "b" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 1, "pp", "mf", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "o", "o", "c" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o", "ab" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o" ], [ "x", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "h", "x", "bb" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "o", "h" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "o", "x" ], [ "o", "o", "o" ], false, 3, 1.5, 2, "ppp", "mf", false),
new OboeFingering(70, [  ], [ "x", "o", "x" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "o", "x", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70, [  ], [ "x", "x", "o", "bb" ], [ "x", "x", "o" ], false, 3, 1.5, 3, "pp", "mf", 43),
new OboeFingering(70, [  ], [ "x", "h", "h", "bb", "f" ], [ "x", "x", "x", "cis" ], false, 2, 1.5, 4, "ppp", "mp", 90),
new OboeFingering(70, [  ], [ "x", "h", "h", "bb", "f" ], [ "x", "x", "h", "cis" ], false, 1, 1.5, 4, "ppp", "mp", 95),
new OboeFingering(70, [  ], [ "x", "h", "h", "bb" ], [ "x", "x", "f", "o" ], false, 1, 1.5, 4, "ppp", "mp", false),
new OboeFingering(70, [  ], [ "x", "h", "h", "b", "f" ], [ "x", "x", "x", "eb" ], false, 2, 1.5, 5, "ppp", "p", 91),
new OboeFingering(70.5, [  ], [ "x", "o", "o", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "pp", "ff", false),
new OboeFingering(70.5, [  ], [ "x", "o", "o", "ab" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70.5, [  ], [ "x", "o", "o", "ab" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70.5, [  ], [ "x", "o", "o", "ab" ], [ "o", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(70.5, [  ], [ "x", "h", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 1, "p", "mf", false),
new OboeFingering(70.5, [  ], [ "x", "o", "x", "bb" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "ppp", "fff", 369),
new OboeFingering(70.5, [  ], [ "x", "o", "x", "b" ], [ "x", "x", "o" ], false, 3, 1.5, 3, "pp", "mp", false),
new OboeFingering(70.5, [  ], [ "x", "o", "x" ], [ "x", "x", "f", "o", "c" ], false, 2, 1.5, 3, "ppp", "mp", 126),
new OboeFingering(70.5, [  ], [ "x", "o", "x" ], [ "x", "x", "o", "cis" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(70.5, [  ], [ "x", "o", "x" ], [ "x", "o", "o" ], false, 1, 1.5, 4, "ppp", "mp", 134),
new OboeFingering(70.5, [  ], [ "x", "o", "h", "b", "f" ], [ "x", "x", "o", "eb" ], false, 3, 1.5, 5, "ppp", "p", 138),
new OboeFingering(70.5, [  ], [ "x", "x", "o" ], [ "x", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "h", "o", "o", "ab" ], [ "abtrill", "o", "o", "o", "c" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "o" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "o" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "o" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "o" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "o", "b" ], [ "o", "x", "x" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "o", "ab" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "o", "ab" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "x" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "o", "o", "ab" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "x", "h", "x", "b" ], [ "x", "x", "x" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(71, [  ], [ "o", "x", "x" ], [ "o", "x", "x" ], false, 1, 1.5, 3, "ppp", "mp", 244),
new OboeFingering(71, [  ], [ "x", "o", "h" ], [ "x", "o", "x" ], false, 1, 1.5, 4, "ppp", "ppp", 142),
new OboeFingering(71, [  ], [ "o", "x", "x" ], [ "o", "o", "o" ], false, 1, 1.5, 4, "ppp", "pp", 265),
new OboeFingering(71, [  ], [ "h", "x", "x", "bb" ], [ "x", "x", "x", "cis" ], false, 1, 1.5, 5, "ppp", "ppp", 149),
new OboeFingering(71, [  ], [ "h", "h", "x", "f" ], [ "x", "x", "h" ], false, 1, 1.5, 5, "ppp", "pp", 207),
new OboeFingering(71, [  ], [ "h", "h", "x" ], [ "x", "o", "o" ], false, 1, 1.5, 5, "ppp", "pp", 212),
new OboeFingering(71, [ 1 ], [ "x", "h", "h" ], [ "x", "x", "o", "eb" ], false, 2, 1.5, 5, "ppp", "ppp", 103),
new OboeFingering(71, [  ], [ "h", "o", "x" ], [ "x", "x", "o", "c" ], false, 1, 1.5, 5, "ppp", "pp", false),
new OboeFingering(71.5, [  ], [ "h", "o", "o" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "p", "mf", false),
new OboeFingering(71.5, [  ], [ "h", "o", "o" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71.5, [  ], [ "h", "o", "o" ], [ "o", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71.5, [  ], [ "h", "o", "o" ], [ "o", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71.5, [  ], [ "x", "o", "o", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(71.5, [  ], [ "h", "o", "o" ], [ "o", "x", "o", "c" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(71.5, [  ], [ "x", "o", "x", "b" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "p", "f", false),
new OboeFingering(71.5, [  ], [ "h", "h", "o", "b" ], [ "x", "x", "f", "o", "c" ], false, 3, 1.5, 3, "pp", "f", false),
new OboeFingering(71.5, [  ], [ "h", "o", "x" ], [ "x", "o", "o" ], false, 1, 1.5, 4, "ppp", "p", 228),
new OboeFingering(71.5, [  ], [ "o", "x", "x", "b" ], [ "o", "x", "x", "cis" ], false, 3, 1.5, 4, "ppp", "pp", false),
new OboeFingering(71.5, [  ], [ "o", "x", "x", "ab" ], [ "o", "x", "x", "c" ], false, 1, 1.5, 4, "ppp", "p", 250),
new OboeFingering(71.5, [  ], [ "o", "x", "x", "ab" ], [ "o", "x", "x", "cis" ], false, 2, 1.5, 4, "ppp", "p", 253),
new OboeFingering(71.5, [  ], [ "h", "h", "h", "f" ], [ "x", "x", "h" ], false, 1, 1.5, 5, "ppp", "ppp", 221),
new OboeFingering(71.5, [  ], [ "h", "o", "x" ], [ "x", "o", "h" ], false, 1, 1.5, 5, "ppp", "ppp", 227),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "o", "o" ], [ "x", "x", "f", "o" ], false, 3, 1.5, 1, "ppp", "fff", 372),
new OboeFingering(72, [  ], [ "x", "o", "x" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "o", "x", "x", "ab" ], [ "o", "x", "x" ], false, 3, 1.5, 3, "ppp", "mp", 255),
new OboeFingering(72, [  ], [ "o", "x", "x", "ab" ], [ "o", "x", "o", "cis" ], false, 3, 1.5, 3, "ppp", "mp", 261),
new OboeFingering(72, [  ], [ "o", "x", "x", "ab" ], [ "o", "x", "o", "eb" ], false, 3, 1.5, 3, "ppp", "mf", 262),
new OboeFingering(72, [  ], [ "o", "h", "x", "f" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 3, "ppp", "mf", 277),
new OboeFingering(72, [  ], [ "o", "h", "x", "b" ], [ "o", "x", "o", "c" ], false, 3, 1.5, 3, "ppp", "mf", 280),
new OboeFingering(72, [  ], [ "o", "h", "x" ], [ "o", "o", "x" ], false, 3, 1.5, 3, "ppp", "pp", 283),
new OboeFingering(72, [  ], [ "o", "x", "x", "f" ], [ "o", "x", "x", "eb" ], false, 1, 1.5, 4, "ppp", "pp", 254),
new OboeFingering(72, [  ], [ "o", "x", "x", "bb" ], [ "o", "x", "o" ], false, 1, 1.5, 4, "ppp", "pp", 257),
new OboeFingering(72, [  ], [ "o", "x", "x", "b" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "o", "x", "x", "ab" ], [ "o", "x", "f", "o", "c" ], false, 1, 1.5, 4, "ppp", "pp", 260),
new OboeFingering(72, [  ], [ "o", "x", "h", "b" ], [ "o", "x", "h", "c" ], false, 1, 1.5, 4, "ppp", "mp", 269),
new OboeFingering(72, [  ], [ "o", "x", "h", "b" ], [ "o", "x", "h", "eb" ], false, 2, 1.5, 4, "ppp", "mp", 270),
new OboeFingering(72, [  ], [ "o", "x", "h", "bb" ], [ "o", "x", "o" ], false, 2, 1.5, 4, "ppp", "mp", 272),
new OboeFingering(72, [  ], [ "o", "h", "x", "b", "f" ], [ "o", "x", "h", "eb" ], false, 3, 1.5, 4, "ppp", "mp", 278),
new OboeFingering(72, [  ], [ "o", "h", "x", "b" ], [ "o", "x", "o" ], false, 3, 1.5, 4, "ppp", "mp", 279),
new OboeFingering(72, [  ], [ "o", "h", "x", "b", "f" ], [ "o", "x", "o" ], false, 3, 1.5, 4, "ppp", "mp", 281),
new OboeFingering(72, [  ], [ "o", "h", "x" ], [ "o", "x", "o", "c" ], false, 3, 1.5, 4, "ppp", "mp", 282),
new OboeFingering(72, [  ], [ "o", "o", "x" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "o", "o", "x" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "o", "o", "x", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "x", "cistrill", "o" ], [ "ab", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72, [  ], [ "x", "x", "cistrill", "x" ], [ "ab", "o", "o", "o" ], false, 2, 1.5, 4, "ppp", "p", 296),
new OboeFingering(72, [  ], [ "x", "x", "cistrill", "h" ], [ "ab", "o", "o", "o" ], false, 2, 1.5, 4, "ppp", "mp", 303),
new OboeFingering(72, [ 1 ], [ "h", "x", "o" ], [ "x", "o", "x", "c" ], false, 1, 1.5, 5, "ppp", "pp", 197),
new OboeFingering(72, [ 1 ], [ "h", "h", "x", "b", "f" ], [ "o", "x", "o", "c" ], false, 1, 1.5, 5, "ppp", "pp", false),
new OboeFingering(72.5, [  ], [ "o", "o", "o", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "o", "o", "o" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "o", "o", "o", "ab" ], [ "x", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "h", "o", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "pp", "f", false),
new OboeFingering(72.5, [  ], [ "h", "o", "o" ], [ "x", "o", "h", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "h", "o", "o" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "h", "o", "o" ], [ "x", "x", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "h", "o", "o" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "h", "o", "o" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "h", "o", "o" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "h", "o", "x" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "h", "o", "o" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 1, "ppp", "fff", 381),
new OboeFingering(72.5, [  ], [ "o", "o", "h", "b", "f" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, 2, "pp", "f", 385),
new OboeFingering(72.5, [  ], [ "o", "o", "h", "b" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "o", "o", "x" ], [ "x", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "o", "o", "x" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "o", "o", "x" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "o", "o", "h" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(72.5, [  ], [ "o", "x", "x" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 3, "ppp", "f", false),
new OboeFingering(72.5, [ 1 ], [ "o", "x", "x", "bb" ], [ "o", "x", "x", "eb" ], false, 1, 1.5, 4, "ppp", "pp", false),
new OboeFingering(72.5, [ 1 ], [ "o", "x", "x", "ab" ], [ "o", "x", "o", "eb" ], false, 3, 1.5, 5, "ppp", "p", 263),
new OboeFingering(73, [  ], [ "o", "o", "h" ], [ "x", "x", "x", "c" ], false, 3, 1.5, -1, "ppp", "f", 386),
new OboeFingering(73, [  ], [ "x", "o", "cistrill", "o" ], [ "x", "o", "o" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "o" ], [ "o", "o", "o" ], false, 3, 1.5, -1, "p", "f", false),
new OboeFingering(73, [  ], [ "o", "o", "o", "b" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "o" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "o" ], [ "x", "x", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "o" ], [ "x", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "o" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "o" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "o" ], [ "x", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "o" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "o", "o", "x" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "h", "x", "x" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, 0, "ppp", "fff", 377),
new OboeFingering(73, [  ], [ "h", "x", "x" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "h", "x", "x", "eb" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [ 1 ], [ "h", "x", "x" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [ 3 ], [ "h", "x", "x" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "h", "o", "x" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "h", "x", "cistrill", "o" ], [ "o", "o", "x", "eb" ], false, 3, 1.5, 3, "ppp", "mp", 391),
new OboeFingering(73, [  ], [ "x", "x", "o" ], [ "o", "dtrill", "x", "o", "eb" ], false, 2, 1.5, 3, "ppp", "mp", 337),
new OboeFingering(73, [ 3 ], [ "x", "x", "o" ], [ "x", "x", "x", "c" ], false, 1, 1.5, 4, "ppp", "p", 37),
new OboeFingering(73, [ 3 ], [ "x", "h", "o", "b" ], [ "x", "x", "o", "f" ], false, 3, 1.5, 4, "ppp", "pp", false),
new OboeFingering(73, [ 1 ], [ "x", "x", "cistrill", "o" ], [ "o", "o", "h", "eb" ], false, 1, 1.5, 4, "ppp", "p", 306),
new OboeFingering(73, [  ], [ "x", "x", "h", "ab" ], [ "o", "dtrill", "x", "h" ], false, 2, 1.5, 4, "ppp", "p", 332),
new OboeFingering(73, [  ], [ "x", "x", "h", "ab" ], [ "o", "dtrill", "o", "o" ], false, 2, 1.5, 4, "ppp", "p", 334),
new OboeFingering(73, [  ], [ "x", "x", "o", "ab" ], [ "o", "dtrill", "x", "h", "c" ], false, 2, 1.5, 4, "ppp", "p", 336),
new OboeFingering(73, [  ], [ "x", "x", "o", "ab" ], [ "o", "dtrill", "x", "o", "eb" ], false, 2, 1.5, 4, "ppp", "p", 338),
new OboeFingering(73, [  ], [ "x", "x", "o" ], [ "o", "dtrill", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "x", "x", "o" ], [ "o", "dtrill", "o", "h", "eb" ], false, 2, 1.5, 4, "ppp", "mp", 339),
new OboeFingering(73, [  ], [ "x", "o", "o", "ab" ], [ "x", "dtrill", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [  ], [ "x", "o", "cistrill", "o" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73, [ 3 ], [ "x", "x", "o", "bb" ], [ "x", "x", "o" ], false, 1, 1.5, 5, "ppp", "pp", 44),
new OboeFingering(73, [ 3 ], [ "x", "x", "o", "b" ], [ "x", "x", "o", "c" ], false, 1, 1.5, 5, "ppp", "pp", 45),
new OboeFingering(73, [ 3 ], [ "x", "x", "o" ], [ "x", "x", "o", "c" ], false, 1, 1.5, 5, "ppp", "pp", 48),
new OboeFingering(73, [ 3 ], [ "x", "x", "o" ], [ "x", "o", "o", "c" ], false, 1, 1.5, 5, "ppp", "pp", 53),
new OboeFingering(73, [ 3 ], [ "x", "h", "h" ], [ "x", "o", "x", "cis" ], false, 1, 1.5, 5, "ppp", "ppp", 104),
new OboeFingering(73, [ 3 ], [ "x", "h", "o" ], [ "x", "x", "o" ], false, 1, 1.5, 5, "ppp", "pp", false),
new OboeFingering(73, [ 3 ], [ "x", "h", "o", "b" ], [ "x", "o", "o", "eb" ], false, 1, 1.5, 5, "ppp", "pp", false),
new OboeFingering(73, [ 3 ], [ "x", "h", "o" ], [ "x", "o", "o" ], false, 1, 1.5, 5, "ppp", "pp", 116),
new OboeFingering(73, [ 3 ], [ "x", "h", "o" ], [ "x", "o", "o", "c" ], false, 1, 1.5, 5, "ppp", "p", 117),
new OboeFingering(73, [ 3 ], [ "x", "h", "o", "ab" ], [ "o", "o", "o" ], false, 1, 1.5, 5, "ppp", "pp", 118),
new OboeFingering(73, [ 3 ], [ "x", "o", "h" ], [ "o", "x", "o", "c" ], false, 2, 1.5, 5, "ppp", "pp", 370),
new OboeFingering(73, [ 3 ], [ "h", "h", "h", "ab" ], [ "o", "o", "o" ], false, 1, 1.5, 5, "ppp", "pp", false),
new OboeFingering(73.5, [  ], [ "h", "o", "cistrill", "o" ], [ "x", "o", "o" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(73.5, [ 1 ], [ "o", "x", "x" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73.5, [ 1 ], [ "o", "x", "x", "ab" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73.5, [ 1 ], [ "h", "x", "x", "ab" ], [ "x", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(73.5, [ 3 ], [ "x", "o", "h", "f" ], [ "x", "o", "x", "cis" ], false, 1, 1.5, 4, "ppp", "pp", 144),
new OboeFingering(73.5, [ 3 ], [ "x", "h", "x", "f" ], [ "x", "o", "x" ], false, 1, 1.5, 4, "ppp", "pp", 146),
new OboeFingering(73.5, [ 3 ], [ "x", "o", "o" ], [ "o", "o", "o" ], false, 1, 1.5, 4, "ppp", "pp", 375),
new OboeFingering(73.5, [ 3 ], [ "x", "o", "h", "f" ], [ "x", "o", "o" ], false, 1, 1.5, 5, "ppp", "pp", 147),
new OboeFingering(74, [  ], [ "x", "o", "o" ], [ "x", "dtrill", "o", "o" ], false, 3, 1.5, -1, "pp", "ff", false),
new OboeFingering(74, [  ], [ "h", "x", "x" ], [ "x", "x", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(74, [  ], [ "x", "o", "o", "b" ], [ "x", "dtrill", "o", "h" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(74, [  ], [ "h", "x", "x", "bb" ], [ "x", "x", "x" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(74, [ 1 ], [ "h", "x", "x", "b" ], [ "x", "x", "x" ], false, 1, 1.5, 3, "ppp", "mp", 150),
new OboeFingering(74, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(74, [  ], [ "h", "h", "h" ], [ "x", "dtrill", "o", "h", "eb" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(74, [ 3 ], [ "o", "x", "x", "b" ], [ "ab", "o", "x", "x", "c" ], false, 1, 1.5, 4, "ppp", "p", 248),
new OboeFingering(74, [ 3 ], [ "x", "x", "cistrill", "o", "ab" ], [ "o", "o", "h", "eb" ], false, 2, 1.5, 4, "ppp", "p", 307),
new OboeFingering(74, [ 3, 1 ], [ "x", "h", "o" ], [ "x", "o", "x" ], false, 1, 1.5, 5, "ppp", "pp", 114),
new OboeFingering(74, [ 3, 1 ], [ "x", "h", "o" ], [ "x", "o", "o" ], false, 1, 1.5, 5, "ppp", "pp", 115),
new OboeFingering(74, [ 3 ], [ "h", "x", "x" ], [ "x", "x", "x", "c" ], false, 2, 1.5, 5, "ppp", "pp", 151),
new OboeFingering(74, [  ], [ "h", "x", "x", "b" ], [ "x", "x", "h", "c" ], false, 2, 1.5, 5, "ppp", "ppp", 153),
new OboeFingering(74.5, [ 1 ], [ "o", "x", "x" ], [ "x", "x", "x" ], false, 3, 1.5, 0, "pp", "f", false),
new OboeFingering(74.5, [ 1 ], [ "h", "x", "x" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(74.5, [ 1 ], [ "h", "x", "x", "bb" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(74.5, [ 1 ], [ "h", "x", "x", "ab" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(74.5, [ 3 ], [ "h", "x", "x" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(74.5, [ 3 ], [ "x", "x", "x" ], [ "x", "x", "x" ], false, 3, 1.5, 1, "pp", "f", 345),
new OboeFingering(74.5, [ 3 ], [ "x", "x", "x", "bb" ], [ "x", "x", "x" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(74.5, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 3, "ppp", "p", 9),
new OboeFingering(74.5, [ 3 ], [ "x", "h", "x", "b" ], [ "x", "x", "h", "cis" ], false, 1, 1.5, 4, "ppp", "pp", 66),
new OboeFingering(74.5, [  ], [ "h", "x", "x" ], [ "x", "x", "h", "c" ], false, 2, 1.5, 4, "ppp", "p", 155),
new OboeFingering(74.5, [  ], [ "h", "o", "o" ], [ "x", "dtrill", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75, [  ], [ "h", "x", "x" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75, [  ], [ "h", "x", "x", "ab" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75, [  ], [ "h", "x", "x", "ab", "eb" ], [ "x", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75, [ 1 ], [ "h", "x", "x", "ab" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75, [  ], [ "h", "x", "x", "bb" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75, [  ], [ "h", "x", "x", "b" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, 1, "ppp", "mf", false),
new OboeFingering(75, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75, [  ], [ "x", "x", "x" ], [ "x", "h", "h", "cis" ], false, 3, 1.5, 2, "f", "f", 13),
new OboeFingering(75, [ 3 ], [ "x", "o", "x", "b" ], [ "x", "x", "x" ], false, 3, 1.5, 3, "ppp", "p", false),
new OboeFingering(75, [  ], [ "h", "x", "x" ], [ "x", "x", "h", "cis" ], false, 2, 1.5, 3, "ppp", "mp", 158),
new OboeFingering(75, [ 2 ], [ "h", "x", "x" ], [ "x", "x", "h", "c" ], false, 1, 1.5, 5, "ppp", "ppp", 156),
new OboeFingering(75.5, [ 3 ], [ "h", "x", "x" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, -1, "ppp", "mf", false),
new OboeFingering(75.5, [  ], [ "h", "x", "x" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75.5, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75.5, [ 1 ], [ "x", "x", "x", "ab" ], [ "x", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75.5, [  ], [ "h", "x", "x", "b" ], [ "x", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(75.5, [  ], [ "h", "x", "x", "bb" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(75.5, [ 2 ], [ "h", "x", "x", "bb" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 2, "ppp", "mf", false),
new OboeFingering(75.5, [ 1 ], [ "h", "x", "x", "b" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(75.5, [  ], [ "h", "x", "x" ], [ "x", "x", "o", "c" ], false, 1, 1.5, 4, "ppp", "mp", 160),
new OboeFingering(75.5, [ 2 ], [ "o", "x", "x" ], [ "x", "x", "h", "cis" ], false, 1, 1.5, 4, "ppp", "p", 235),
new OboeFingering(75.5, [ 2 ], [ "h", "x", "x", "b" ], [ "x", "x", "o", "c" ], false, 2, 1.5, 5, "ppp", "p", 379),
new OboeFingering(76, [ 3 ], [ "h", "x", "x" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, -1, "ppp", "mf", false),
new OboeFingering(76, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(76, [ 1 ], [ "x", "x", "x", "ab" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(76, [ 1 ], [ "x", "x", "x", "b" ], [ "x", "dtrill", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(76, [ 1 ], [ "h", "x", "x" ], [ "x", "x", "o" ], false, 3, 1.5, 1, "ppp", "f", false),
new OboeFingering(76, [ 1 ], [ "x", "x", "x", "bb" ], [ "x", "x", "o" ], false, 3, 1.5, 2, "ppp", "f", false),
new OboeFingering(76, [ 1 ], [ "x", "x", "x", "b" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(76, [  ], [ "x", "x", "x" ], [ "x", "x", "o", "c" ], false, 4, 1.5, 2, "f", "f", false),
new OboeFingering(76, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 2, "ppp", "f", false),
new OboeFingering(76, [ 2 ], [ "x", "x", "x" ], [ "x", "dtrill", "x", "o", "c" ], false, 3, 1.5, 3, "ppp", "mp", false),
new OboeFingering(76, [ 1 ], [ "h", "x", "x" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 3, "ppp", "p", false),
new OboeFingering(76, [ 2 ], [ "h", "x", "x" ], [ "x", "x", "o", "c" ], false, 1, 1.5, 4, "ppp", "pp", 161),
new OboeFingering(76.5, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "o", "eb" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(76.5, [ 1 ], [ "x", "x", "x" ], [ "x", "h", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(76.5, [ 1 ], [ "h", "x", "x" ], [ "x", "x", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(76.5, [ 3 ], [ "h", "x", "x" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(76.5, [ 1 ], [ "x", "x", "x", "bb" ], [ "x", "x", "o", "eb" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(76.5, [  ], [ "x", "x", "x", "f" ], [ "x", "dtrill", "x", "x" ], false, 3, 1.5, 3, "mp", "mf", 323),
new OboeFingering(76.5, [  ], [ "h", "x", "x", "f" ], [ "x", "x", "h", "cis" ], false, 1, 1.5, 4, "ppp", "p", false),
new OboeFingering(76.5, [ 2 ], [ "h", "x", "x" ], [ "x", "x", "h", "eb" ], false, 1, 2, 5, "ppp", "p", 159),
new OboeFingering(77, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "f", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "f", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77, [ 1 ], [ "x", "x", "x", "bb" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77, [ 1 ], [ "x", "x", "x", "ab" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77, [  ], [ "x", "x", "x", "f" ], [ "x", "x", "h", "c" ], false, 4, 1.5, 1, "f", "ff", 10),
new OboeFingering(77, [ 1 ], [ "x", "x", "x" ], [ "x", "o", "x" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(77, [ 1 ], [ "x", "x", "x" ], [ "x", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77, [ 2 ], [ "x", "x", "x", "bb" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "ppp", "f", false),
new OboeFingering(77, [ 1 ], [ "x", "x", "h", "b" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 3, "ppp", "mp", 361),
new OboeFingering(77, [ 1 ], [ "x", "h", "x", "b" ], [ "x", "x", "o" ], false, 3, 1.5, 3, "ppp", "mp", false),
new OboeFingering(77, [ 1 ], [ "x", "h", "x" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 4, "ppp", "mp", false),
new OboeFingering(77, [ 2 ], [ "h", "x", "x", "b" ], [ "x", "x", "f", "o", "c" ], false, 1, 1.5, 4, "ppp", "mf", false),
new OboeFingering(77, [  ], [ "h", "x", "x" ], [ "x", "x", "f", "o" ], false, 1, 1.5, 5, "pp", "mf", 163),
new OboeFingering(77, [  ], [ "h", "x", "x" ], [ "x", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77, [ 2 ], [ "o", "x", "x" ], [ "x", "x", "o" ], false, 1, 1.5, 5, "ppp", "p", 239),
new OboeFingering(77.5, [  ], [ "x", "x", "x", "f" ], [ "x", "x", "o", "c" ], false, 5, 1.5, -1, "mf", "f", false),
new OboeFingering(77.5, [ 1 ], [ "h", "x", "x" ], [ "x", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77.5, [ 1 ], [ "x", "x", "x" ], [ "x", "o", "h", "eb" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(77.5, [ 1 ], [ "x", "x", "x", "ab" ], [ "x", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77.5, [ 1 ], [ "h", "x", "x" ], [ "x", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77.5, [ 1 ], [ "x", "x", "x" ], [ "x", "x", "f", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77.5, [ 1 ], [ "x", "x", "x", "f" ], [ "x", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77.5, [ 1 ], [ "x", "x", "x" ], [ "x", "o", "h" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(77.5, [ 1 ], [ "x", "x", "x", "b" ], [ "x", "o", "h" ], false, 3, 1.5, 1, "ppp", "f", false),
new OboeFingering(77.5, [ 1 ], [ "x", "x", "x", "f" ], [ "x", "o", "x" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(77.5, [ 2 ], [ "x", "x", "x", "bb" ], [ "x", "o", "x", "c" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(77.5, [ 1 ], [ "x", "x", "x", "bb" ], [ "o", "x", "x" ], false, 3, 1.5, 3, "ppp", "pp", 15),
new OboeFingering(77.5, [ 2 ], [ "x", "h", "x", "b" ], [ "x", "x", "o" ], false, 1, 1.5, 4, "ppp", "mp", 69),
new OboeFingering(78, [  ], [ "x", "x", "x", "f" ], [ "x", "o", "x", "eb" ], false, 3, 1.5, -1, "ff", "ff", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x", "f" ], [ "x", "o", "x", "eb" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x", "f" ], [ "x", "o", "h", "eb" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x" ], [ "x", "o", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x", "b" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x", "bb" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x", "ab" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x" ], [ "x", "o", "o", "eb" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(78, [ 2 ], [ "x", "x", "x", "b" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "ppp", "f", 347),
new OboeFingering(78, [ 1 ], [ "x", "x", "x" ], [ "o", "x", "x" ], false, 3, 1.5, 3, "ppp", "mp", false),
new OboeFingering(78, [ 1 ], [ "x", "x", "x" ], [ "o", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(78, [ 2 ], [ "x", "x", "x" ], [ "o", "x", "x" ], false, 3, 1.5, 3, "ppp", "mp", 356),
new OboeFingering(78, [ 1 ], [ "x", "x", "x", "bb" ], [ "o", "x", "x" ], false, 3, 1.5, 3, "ppp", "mf", 15),
new OboeFingering(78, [ 2 ], [ "x", "x", "h", "bb" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 4, "ppp", "mp", false),
new OboeFingering(78, [ 2 ], [ "x", "x", "h", "bb" ], [ "x", "x", "h", "eb" ], false, 1, 1.5, 4, "ppp", "pp", 25),
new OboeFingering(78, [ 2 ], [ "h", "x", "h" ], [ "x", "x", "o" ], false, 1, 1.5, 5, "ppp", "pp", 186),
new OboeFingering(78.5, [  ], [ "x", "x", "x", "f" ], [ "x", "o", "o", "eb" ], false, 5, 1.5, -1, "ppp", "fff", false),
new OboeFingering(78.5, [ 1 ], [ "x", "x", "x" ], [ "o", "x", "o" ], false, 3, 1.5, 0, "ppp", "f", false),
new OboeFingering(78.5, [ 1 ], [ "x", "x", "x" ], [ "o", "x", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(78.5, [ 1 ], [ "x", "x", "x", "bb" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(78.5, [ 1 ], [ "x", "x", "x" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 1, "pp", "mf", false),
new OboeFingering(78.5, [ 1 ], [ "x", "x", "x", "b" ], [ "o", "x", "o" ], false, 3, 1.5, 1, "ppp", "f", false),
new OboeFingering(78.5, [ 2 ], [ "x", "x", "x", "b" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 2, "ppp", "mf", false),
new OboeFingering(78.5, [ 1 ], [ "x", "x", "h", "bb" ], [ "x", "o", "h", "eb" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(78.5, [ 1 ], [ "x", "x", "h", "bb" ], [ "x", "o", "h", "c" ], false, 3, 1.5, 4, "ppp", "p", false),
new OboeFingering(78.5, [ 1 ], [ "x", "x", "h" ], [ "x", "o", "h", "c" ], false, 1, 1.5, 5, "ppp", "pp", false),
new OboeFingering(79, [  ], [ "x", "x", "x", "f" ], [ "o", "x", "o", "eb" ], false, 5, 1.5, -1, "ff", "ff", false),
new OboeFingering(79, [ 1 ], [ "x", "x", "x" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79, [ 1 ], [ "x", "x", "x" ], [ "o", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79, [ 1 ], [ "x", "x", "x", "bb" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79, [ 1 ], [ "x", "x", "x" ], [ "o", "o", "o", "c" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(79, [ 1 ], [ "x", "x", "x" ], [ "o", "o", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79, [ 1 ], [ "x", "x", "x" ], [ "o", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79, [ 1 ], [ "x", "x", "x" ], [ "o", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79, [ 1 ], [ "x", "x", "x", "b" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79, [ 2 ], [ "x", "x", "x" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79, [ 2 ], [ "x", "x", "x" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "ppp", "f", 2),
new OboeFingering(79, [ 1 ], [ "x", "x", "h" ], [ "o", "x", "x" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(79, [ 2 ], [ "x", "h", "x", "f" ], [ "x", "x", "o", "eb" ], false, 3, 1.5, 4, "ppp", "p", 76),
new OboeFingering(79, [ 2 ], [ "x", "h", "x" ], [ "x", "x", "f", "o" ], false, 3, 1.5, 4, "ppp", "p", false),
new OboeFingering(79, [ 2 ], [ "x", "x", "x" ], [ "x", "dtrill", "o", "f", "o", "eb" ], false, 3, 1.5, 4, "ppp", "mp", 326),
new OboeFingering(79, [  ], [ "h", "x", "x" ], [ "o", "x", "h" ], false, 1, 1.5, 5, "ppp", "pp", 173),
new OboeFingering(79, [ 1 ], [ "h", "x", "x", "bb" ], [ "o", "x", "o", "c" ], false, 1, 1.5, 5, "ppp", "ppp", false),
new OboeFingering(79.5, [  ], [ "x", "x", "x", "f" ], [ "o", "o", "o", "eb" ], false, 5, 1.5, -1, "ff", "ff", false),
new OboeFingering(79.5, [ 1 ], [ "x", "x", "h" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "pp", "f", false),
new OboeFingering(79.5, [ 1 ], [ "x", "x", "h" ], [ "o", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79.5, [ 1 ], [ "x", "x", "h", "bb" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79.5, [ 2 ], [ "x", "x", "h" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79.5, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "x", "x" ], false, 3, 1.5, 1, "pp", "mf", 20),
new OboeFingering(79.5, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79.5, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "x", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(79.5, [ 1 ], [ "x", "x", "h", "bb" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 2, "ppp", "mf", false),
new OboeFingering(79.5, [ 1 ], [ "x", "x", "h", "bb" ], [ "o", "x", "x", "cis" ], false, 3, 1.5, 3, "ppp", "mp", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 2 ], [ "x", "x", "x", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x" ], [ "abtrill", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "o", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "o", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80, [  ], [ "x", "x", "h", "b" ], [ "o", "x", "o", "c" ], false, 5, 1.5, 1, "ff", "ff", false),
new OboeFingering(80, [ 2 ], [ "x", "x", "x" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(80, [ 1 ], [ "x", "x", "h", "ab" ], [ "o", "x", "x" ], false, 3, 1.5, 2, "ppp", "p", false),
new OboeFingering(80, [ 1 ], [ "x", "h", "x", "bb" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 3, "ppp", "p", 88),
new OboeFingering(80, [ 2 ], [ "x", "x", "cistrill", "x" ], [ "o", "o", "o" ], false, 3, 1.5, 3, "ppp", "mp", 390),
new OboeFingering(80, [ 1 ], [ "x", "x", "h" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 4, "ppp", "p", false),
new OboeFingering(80, [ 1 ], [ "x", "h", "x" ], [ "x", "o", "o" ], false, 3, 1.5, 4, "ppp", "p", false),
new OboeFingering(80, [ 2 ], [ "x", "h", "h" ], [ "x", "x", "f", "o" ], false, 3, 1.5, 4, "ppp", "p", false),
new OboeFingering(80.5, [  ], [ "x", "x", "h", "b" ], [ "o", "x", "o", "eb" ], false, 5, 1.5, -1, "ff", "ff", false),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "h", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", 33),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "h" ], [ "ab", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "h", "bb" ], [ "ab", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "h", "ab" ], [ "o", "x", "o" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "x", "ab" ], [ "o", "x", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "h", "ab" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "h", "ab" ], [ "o", "o", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80.5, [ 2 ], [ "x", "x", "h" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(80.5, [ 2 ], [ "x", "x", "h" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(80.5, [ 2 ], [ "x", "x", "o" ], [ "o", "x", "x" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(80.5, [ 1, 2 ], [ "h", "x", "x", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "h" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 4, "pp", "mp", false),
new OboeFingering(80.5, [ 1 ], [ "x", "x", "h", "ab" ], [ "o", "x", "x", "cis" ], false, 3, 1.5, 4, "ppp", "mp", false),
new OboeFingering(80.5, [ 1 ], [ "x", "h", "x", "b" ], [ "o", "x", "x", "c" ], false, 3, 1.5, 4, "ppp", "mp", false),
new OboeFingering(80.5, [ 2 ], [ "h", "x", "x", "ab" ], [ "o", "x", "x", "eb" ], false, 1, 1.5, 5, "ppp", "p", false),
new OboeFingering(80.5, [  ], [ "h", "x", "h", "b" ], [ "o", "x", "x", "c" ], false, 1, 1.5, 5, "ppp", "pp", 192),
new OboeFingering(81, [ 1 ], [ "x", "x", "o" ], [ "abtrill", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(81, [ 2 ], [ "x", "x", "o" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(81, [ 2 ], [ "x", "x", "o" ], [ "abtrill", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(81, [ 2 ], [ "x", "x", "o" ], [ "o", "o", "x" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(81, [ 2 ], [ "x", "x", "x" ], [ "x", "x", "x" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(81, [ 2 ], [ "x", "x", "o" ], [ "o", "x", "o", "c" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(81, [ 2 ], [ "h", "x", "x", "ab" ], [ "o", "x", "f", "o" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(81, [  ], [ "h", "x", "x", "ab" ], [ "o", "x", "h", "c" ], false, 1, 1.5, 4, "mp", "mp", 174),
new OboeFingering(81, [  ], [ "h", "x", "x", "ab" ], [ "o", "o", "o", "eb" ], false, 1, 1.5, 4, "p", "mp", 181),
new OboeFingering(81, [  ], [ "h", "x", "h" ], [ "o", "x", "h", "c" ], false, 1, 1.5, 4, "mp", "mp", 194),
new OboeFingering(81, [ 2 ], [ "h", "h", "x", "b" ], [ "o", "x", "f", "o", "c" ], false, 1, 1.5, 5, "ppp", "pp", false),
new OboeFingering(81.5, [ 2 ], [ "x", "x", "o", "ab" ], [ "o", "x", "x", "cis" ], false, 3, 1.5, -1, "ppp", "fff", false),
new OboeFingering(81.5, [ 2 ], [ "x", "x", "o", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(81.5, [ 2 ], [ "x", "x", "o" ], [ "ab", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(81.5, [ 2 ], [ "x", "x", "o", "ab" ], [ "o", "x", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(81.5, [ 2 ], [ "x", "x", "o", "ab" ], [ "o", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(81.5, [ 2 ], [ "x", "x", "o", "bb" ], [ "ab", "o", "o", "o", "c" ], false, 3, 1.5, 1, "pp", "ff", false),
new OboeFingering(81.5, [ 2 ], [ "x", "x", "h" ], [ "x", "x", "x" ], false, 3, 1.5, 2, "ppp", "fff", 21),
new OboeFingering(81.5, [  ], [ "x", "h", "x" ], [ "x", "x", "x" ], false, 2, 1.5, 3, "ppp", "fff", 54),
new OboeFingering(81.5, [ 2 ], [ "x", "h", "x", "bb" ], [ "ab", "o", "x", "x", "c" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(81.5, [ 2 ], [ "x", "h", "x", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(82, [  ], [ "x", "x", "o", "b" ], [ "ab", "o", "x", "x", "c" ], false, 5, 1.5, -1, "ff", "ff", 367),
new OboeFingering(82, [ 2 ], [ "x", "x", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82, [  ], [ "x", "x", "h" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, 1, "mf", "f", 23),
new OboeFingering(82, [  ], [ "x", "x", "h", "b" ], [ "x", "x", "h" ], false, 3, 1.5, 1, "mf", "f", 26),
new OboeFingering(82, [ 1 ], [ "x", "x", "o", "b" ], [ "x", "x", "f", "o", "c" ], false, 3, 1.5, 1, "p", "mf", 46),
new OboeFingering(82, [ 1 ], [ "x", "x", "o" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82, [  ], [ "x", "o", "x" ], [ "x", "x", "x", "cis" ], false, 3, 2, 1, "mf", "mf", 121),
new OboeFingering(82, [ 2 ], [ "x", "x", "x", "bb" ], [ "x", "x", "x", "c" ], false, 5, 1.5, 2, "mf", "f", false),
new OboeFingering(82, [ 2 ], [ "x", "x", "x" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(82, [  ], [ "x", "h", "h" ], [ "x", "x", "x", "c" ], false, 4, 2, 2, "mf", "mf", 92),
new OboeFingering(82, [ 1 ], [ "x", "h", "h" ], [ "o", "x", "h", "c" ], false, 4, 1.5, 2, "mp", "mf", 107),
new OboeFingering(82, [ 2 ], [ "x", "o", "x" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, 3, "pp", "mp", 122),
new OboeFingering(82, [ 2 ], [ "x", "x", "o" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82, [ 2 ], [ "x", "x", "o" ], [ "x", "o", "o", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82, [ 2 ], [ "x", "o", "x" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82, [ 2 ], [ "x", "o", "o" ], [ "abtrill", "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82, [ 1 ], [ "x", "o", "x", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82, [ 2 ], [ "x", "o", "h", "b" ], [ "o", "x", "o" ], false, 3, 1.5, 3, "ppp", "mp", false),
new OboeFingering(82, [ 2 ], [ "h", "x", "o" ], [ "x", "o", "x", "c" ], false, 1, 1.5, 4, "ppp", "p", false),
new OboeFingering(82, [ 2 ], [ "h", "o", "x" ], [ "o", "x", "x", "c" ], false, 1, 1.5, 4, "ppp", "p", false),
new OboeFingering(82, [ 2 ], [ "h", "h", "h", "bb" ], [ "o", "x", "x", "cis" ], false, 1, 1.5, 5, "ppp", "p", false),
new OboeFingering(82.5, [ 2 ], [ "x", "o", "o", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82.5, [ 1 ], [ "x", "o", "o", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82.5, [ 2 ], [ "x", "o", "o", "ab" ], [ "o", "x", "o", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82.5, [ 2 ], [ "x", "o", "o", "ab" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82.5, [ 1 ], [ "x", "o", "o", "ab" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(82.5, [  ], [ "x", "x", "h", "bb" ], [ "x", "x", "x", "eb" ], false, 3, 2, 1, "mf", "f", 22),
new OboeFingering(82.5, [ 2 ], [ "x", "h", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 1, "pp", "mf", false),
new OboeFingering(82.5, [ 2 ], [ "x", "x", "x" ], [ "x", "x", "h", "eb" ], false, 3, 2, 2, "ppp", "fff", false),
new OboeFingering(82.5, [  ], [ "x", "h", "x", "bb" ], [ "x", "x", "x" ], false, 4, 1.5, 2, "mf", "f", 55),
new OboeFingering(82.5, [  ], [ "x", "h", "x", "b" ], [ "x", "x", "h" ], false, 3, 1.5, 2, "ppp", "f", false),
new OboeFingering(82.5, [ 2 ], [ "x", "o", "h" ], [ "x", "o", "x", "c" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(82.5, [ 2 ], [ "x", "o", "h", "b" ], [ "o", "x", "x" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(82.5, [ 1 ], [ "x", "x", "o" ], [ "x", "x", "x", "cis" ], false, 4, 1.5, 4, "mp", "mf", 39),
new OboeFingering(82.5, [ 1 ], [ "x", "x", "o" ], [ "x", "o", "o", "c" ], false, 4, 1.5, 4, "mp", "mf", 52),
new OboeFingering(83, [ 1 ], [ "x", "h", "o" ], [ "x", "x", "f", "o" ], false, 4, 1.5, -1, "mf", "f", 112),
new OboeFingering(83, [ 2 ], [ "x", "o", "o" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83, [ 2 ], [ "x", "o", "o" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83, [ 2 ], [ "x", "o", "o" ], [ "o", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83, [ 2 ], [ "x", "o", "o", "ab" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83, [  ], [ "x", "x", "h", "bb" ], [ "x", "x", "h", "eb" ], false, 4, 1.5, 1, "mf", "mf", 24),
new OboeFingering(83, [ 2 ], [ "x", "x", "x" ], [ "x", "x", "o" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(83, [  ], [ "x", "h", "x" ], [ "x", "x", "o" ], false, 5, 1.5, 2, "mf", "mf", false),
new OboeFingering(83, [  ], [ "x", "h", "x", "b" ], [ "x", "x", "o" ], false, 5, 1.5, 2, "mf", "f", false),
new OboeFingering(83, [ 2 ], [ "x", "x", "h", "bb" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 3, "pp", "mp", 25),
new OboeFingering(83, [  ], [ "x", "h", "x", "bb" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 3, "mp", "mf", 61),
new OboeFingering(83, [ 2 ], [ "x", "h", "x", "bb" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 3, "pp", "mp", 63),
new OboeFingering(83, [ 2 ], [ "x", "h", "x", "b" ], [ "x", "x", "h", "cis" ], false, 3, 1.5, 3, "pp", "mp", 65),
new OboeFingering(83, [ 2 ], [ "h", "h", "h", "bb" ], [ "x", "x", "x", "eb" ], false, 3, 1.5, 3, "ppp", "mf", false),
new OboeFingering(83, [ 2 ], [ "x", "h", "x", "b" ], [ "x", "x", "h", "c" ], false, 1, 1.5, 4, "ppp", "pp", false),
new OboeFingering(83, [  ], [ "h", "x", "h" ], [ "x", "x", "o" ], false, 3, 1.5, 4, "ppp", "mf", false),
new OboeFingering(83, [ 2 ], [ "h", "h", "x", "bb" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 4, "ppp", "mf", false),
new OboeFingering(83, [  ], [ "h", "h", "x", "bb" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 4, "pp", "mp", 203),
new OboeFingering(83.5, [ 2 ], [ "h", "o", "o" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "pp", "f", false),
new OboeFingering(83.5, [ 2 ], [ "o", "o", "h" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83.5, [ 2 ], [ "o", "x", "o" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83.5, [ 2 ], [ "h", "o", "o" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83.5, [ 2 ], [ "h", "o", "o" ], [ "o", "x", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83.5, [ 2 ], [ "o", "x", "o", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83.5, [ 2 ], [ "x", "x", "x" ], [ "x", "x", "o", "eb" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(83.5, [  ], [ "x", "x", "h" ], [ "x", "x", "o", "eb" ], false, 4, 1.5, 1, "mf", "f", 30),
new OboeFingering(83.5, [  ], [ "x", "h", "x", "b" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 1, "p", "mp", 64),
new OboeFingering(83.5, [  ], [ "x", "h", "x" ], [ "x", "x", "o" ], false, 5, 1.5, 1, "mf", "f", false),
new OboeFingering(83.5, [ 2 ], [ "x", "h", "x", "bb" ], [ "x", "x", "o", "eb" ], false, 3, 1.5, 2, "pp", "mp", false),
new OboeFingering(83.5, [ 2 ], [ "x", "h", "x", "b" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 2, "ppp", "mp", 70),
new OboeFingering(83.5, [ 2 ], [ "x", "o", "x", "b" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "pp", "mp", false),
new OboeFingering(83.5, [ 2 ], [ "h", "x", "x" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 2, "pp", "mp", 159),
new OboeFingering(83.5, [  ], [ "h", "x", "h", "b" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 2, "ppp", "mf", 184),
new OboeFingering(83.5, [  ], [ "h", "x", "h" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(83.5, [  ], [ "x", "h", "x", "bb" ], [ "x", "x", "o", "eb" ], false, 4, 1.5, 3, "mp", "mf", false),
new OboeFingering(83.5, [ 2 ], [ "x", "h", "h", "b" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 3, "p", "mp", 96),
new OboeFingering(83.5, [ 2 ], [ "h", "x", "x", "b" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 3, "ppp", "mf", 379),
new OboeFingering(84, [ 2 ], [ "x", "o", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(84, [ 2 ], [ "x", "x", "o" ], [ "x", "dtrill", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(84, [ 2 ], [ "x", "o", "o" ], [ "x", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(84, [ 2 ], [ "x", "o", "o" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(84, [ 2 ], [ "x", "o", "o" ], [ "x", "x", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(84, [  ], [ "x", "h", "x" ], [ "x", "x", "o", "eb" ], false, 5, 1.5, 1, "mf", "ff", false),
new OboeFingering(84, [  ], [ "x", "h", "h" ], [ "x", "x", "o", "eb" ], false, 4, 1.5, 1, "mf", "ff", 102),
new OboeFingering(84, [ 2 ], [ "x", "o", "o" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 1, "ppp", "fff", false),
new OboeFingering(84, [  ], [ "x", "o", "x", "f" ], [ "x", "x", "x" ], false, 5, 1.5, 2, "mf", "f", false),
new OboeFingering(84, [ 2 ], [ "x", "o", "x" ], [ "x", "o", "x" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(84, [ 2 ], [ "x", "o", "x", "b" ], [ "x", "o", "x", "eb" ], false, 3, 1.5, 2, "mp", "f", false),
new OboeFingering(84, [ 2 ], [ "x", "x", "x" ], [ "x", "x", "f", "o" ], false, 3, 1.5, 3, "p", "f", false),
new OboeFingering(84, [ 2 ], [ "o", "x", "x" ], [ "x", "x", "h", "eb" ], false, 3, 1.5, 3, "pp", "mf", 237),
new OboeFingering(84, [ 2 ], [ "h", "x", "x", "b" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 4, "pp", "mf", false),
new OboeFingering(84, [  ], [ "h", "h", "x", "bb" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 4, "ppp", "mf", false),
new OboeFingering(84.5, [ 2 ], [ "x", "o", "cistrill", "o", "ab" ], [ "x", "o", "o", "eb" ], false, 3, 1.5, -1, "p", "f", false),
new OboeFingering(84.5, [ 2 ], [ "o", "o", "o" ], [ "o", "o", "o" ], false, 3, 1.5, -1, "p", "mf", false),
new OboeFingering(84.5, [ 2 ], [ "o", "o", "o", "ab" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(84.5, [ 2 ], [ "h", "o", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "pp", "ff", false),
new OboeFingering(84.5, [ 2 ], [ "h", "o", "o" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(84.5, [ 2 ], [ "h", "o", "o" ], [ "x", "x", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(84.5, [  ], [ "x", "h", "x", "b" ], [ "x", "x", "f", "o", "c" ], false, 4, 1.5, 1, "f", "f", 71),
new OboeFingering(84.5, [  ], [ "x", "h", "x", "f" ], [ "x", "x", "o", "eb" ], false, 4, 1.5, 1, "mp", "f", 75),
new OboeFingering(84.5, [  ], [ "x", "o", "x", "bb" ], [ "x", "x", "f", "o", "c" ], false, 4, 1.5, 1, "mf", "f", 124),
new OboeFingering(84.5, [  ], [ "h", "h", "x" ], [ "x", "x", "h", "c" ], false, 4, 1.5, 1, "p", "f", 204),
new OboeFingering(84.5, [  ], [ "h", "h", "x", "bb" ], [ "x", "x", "f", "o", "c" ], false, 3, 1.5, 1, "pp", "mp", false),
new OboeFingering(84.5, [  ], [ "h", "h", "x", "b" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 1, "p", "f", false),
new OboeFingering(84.5, [  ], [ "o", "x", "x", "bb" ], [ "x", "x", "o" ], false, 3, 1.5, 1, "p", "mf", false),
new OboeFingering(84.5, [  ], [ "o", "x", "x", "b" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 1, "p", "mf", 240),
new OboeFingering(84.5, [  ], [ "x", "h", "x", "b", "f" ], [ "x", "x", "x", "c" ], false, 4, 1.5, 2, "p", "f", 59),
new OboeFingering(84.5, [ 2 ], [ "x", "h", "x", "f" ], [ "x", "x", "o", "eb" ], false, 4, 1.5, 2, "mf", "f", 76),
new OboeFingering(84.5, [  ], [ "x", "h", "x", "bb" ], [ "x", "o", "x" ], false, 4, 1.5, 2, "mf", "f", 79),
new OboeFingering(84.5, [  ], [ "x", "o", "x", "f" ], [ "x", "x", "x", "eb" ], false, 4, 1.5, 2, "mp", "ff", 123),
new OboeFingering(84.5, [ 2 ], [ "x", "o", "x" ], [ "x", "x", "f", "o", "c" ], false, 4, 1.5, 2, "pp", "mp", 127),
new OboeFingering(84.5, [ 2 ], [ "h", "x", "x" ], [ "x", "x", "x", "c" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(84.5, [ 2 ], [ "h", "x", "x" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 2, "p", "f", 161),
new OboeFingering(84.5, [  ], [ "h", "x", "h" ], [ "x", "x", "f", "o" ], false, 3, 1.5, 2, "pp", "f", 190),
new OboeFingering(84.5, [  ], [ "h", "h", "x" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 2, "ppp", "mf", 204),
new OboeFingering(84.5, [  ], [ "o", "x", "x" ], [ "x", "x", "h", "eb" ], false, 4, 1.5, 2, "p", "f", 236),
new OboeFingering(84.5, [  ], [ "o", "x", "x" ], [ "x", "x", "o" ], false, 4, 1.5, 2, "p", "mf", 238),
new OboeFingering(84.5, [  ], [ "x", "h", "x" ], [ "x", "o", "x" ], false, 4, 1.5, 3, "p", "f", 78),
new OboeFingering(84.5, [  ], [ "h", "h", "x", "f" ], [ "x", "x", "h" ], false, 4, 1.5, 3, "pp", "mf", 207),
new OboeFingering(84.5, [  ], [ "h", "h", "x" ], [ "x", "o", "x" ], false, 4, 1.5, 4, "p", "mf", 210),
new OboeFingering(84.5, [  ], [ "h", "h", "h", "f" ], [ "x", "x", "h" ], false, 4, 1.5, 4, "pp", "mf", 221),
new OboeFingering(84.5, [  ], [ "h", "h", "h" ], [ "x", "o", "x" ], false, 4, 1.5, 4, "mp", "mf", 224),
new OboeFingering(85, [ 2 ], [ "o", "o", "o" ], [ "x", "o", "o" ], false, 3, 1.5, -1, "p", "ff", false),
new OboeFingering(85, [ 2 ], [ "x", "o", "o" ], [ "x", "dtrill", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85, [ 2 ], [ "x", "o", "cistrill", "o" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85, [ 2 ], [ "o", "o", "cistrill", "o" ], [ "x", "o", "o" ], false, 3, 1.5, -1, "pp", "ff", false),
new OboeFingering(85, [  ], [ "o", "x", "x" ], [ "x", "o", "o", "c" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85, [  ], [ "o", "x", "x" ], [ "x", "o", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85, [  ], [ "o", "x", "x" ], [ "x", "x", "h", "c" ], false, 4, 1.5, 1, "mf", "f", 230),
new OboeFingering(85, [  ], [ "h", "x", "x" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85, [  ], [ "h", "x", "x", "ab" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85, [ 2 ], [ "o", "x", "x" ], [ "x", "x", "h", "c" ], false, 4, 1.5, 1, "mf", "f", 232),
new OboeFingering(85, [ 2 ], [ "o", "h", "x" ], [ "x", "x", "h", "c" ], false, 3, 1.5, 1, "pp", "f", 276),
new OboeFingering(85, [ 2 ], [ "x", "x", "cistrill", "x" ], [ "x", "x", "h", "c" ], false, 4, 1.5, 1, "f", "f", 285),
new OboeFingering(85, [  ], [ "x", "x", "x", "f" ], [ "x", "x", "x", "c" ], false, 5, 1.5, 2, "f", "f", false),
new OboeFingering(85, [  ], [ "x", "h", "x" ], [ "x", "x", "h", "c" ], false, 4, 1.5, 2, "f", "f", 68),
new OboeFingering(85, [  ], [ "x", "h", "x", "bb", "f" ], [ "x", "o", "x" ], false, 4, 1.5, 2, "f", "f", 80),
new OboeFingering(85, [  ], [ "x", "h", "x", "bb" ], [ "x", "o", "h" ], false, 3, 1.5, 2, "mf", "f", 82),
new OboeFingering(85, [  ], [ "x", "o", "x" ], [ "x", "o", "h" ], false, 4, 1.5, 2, "f", "f", 132),
new OboeFingering(85, [  ], [ "h", "h", "x", "b" ], [ "x", "x", "f", "o", "c" ], false, 5, 1.5, 2, "p", "f", false),
new OboeFingering(85, [  ], [ "h", "h", "x", "f" ], [ "x", "o", "x" ], false, 4, 1.5, 2, "p", "f", 211),
new OboeFingering(85, [  ], [ "h", "x", "x" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85, [  ], [ "h", "h", "h", "bb", "f" ], [ "x", "x", "o" ], false, 4, 1.5, 2, "mp", "f", 222),
new OboeFingering(85, [  ], [ "h", "o", "x", "f" ], [ "x", "o", "x" ], false, 4, 1.5, 2, "p", "f", 226),
new OboeFingering(85, [  ], [ "h", "x", "h" ], [ "x", "x", "f", "o", "c" ], false, 3, 1.5, 3, "pp", "mf", 189),
new OboeFingering(85, [  ], [ "h", "h", "x", "b" ], [ "x", "x", "f", "o", "c" ], false, 5, 1.5, 3, "p", "f", false),
new OboeFingering(85, [  ], [ "h", "h", "h" ], [ "x", "x", "f", "o" ], false, 4, 1.5, 3, "p", "f", 223),
new OboeFingering(85, [  ], [ "h", "o", "h" ], [ "x", "x", "f", "o" ], false, 4, 1.5, 3, "p", "f", 229),
new OboeFingering(85.5, [  ], [ "o", "x", "x" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "p", "ff", false),
new OboeFingering(85.5, [  ], [ "o", "x", "x", "b" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85.5, [  ], [ "o", "x", "x", "bb" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85.5, [  ], [ "h", "x", "x" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85.5, [  ], [ "h", "x", "x", "ab" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85.5, [  ], [ "h", "x", "x" ], [ "o", "dtrill", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85.5, [ 2 ], [ "h", "o", "o", "ab" ], [ "x", "dtrill", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(85.5, [  ], [ "h", "x", "x" ], [ "x", "h", "h", "cis" ], false, 4, 1.5, 1, "f", "ff", 164),
new OboeFingering(85.5, [  ], [ "o", "o", "h", "b" ], [ "x", "x", "x" ], false, 5, 1.5, 1, "ff", "ff", 384),
new OboeFingering(85.5, [ 2 ], [ "x", "o", "cistrill", "x" ], [ "x", "o", "x" ], false, 3, 1.5, 1, "p", "ff", false),
new OboeFingering(85.5, [  ], [ "h", "h", "x" ], [ "x", "o", "o" ], false, 4, 1.5, 2, "p", "ff", 212),
new OboeFingering(86, [  ], [ "o", "x", "x", "bb" ], [ "o", "x", "o" ], false, 4, 1.5, -1, "f", "ff", 257),
new OboeFingering(86, [  ], [ "x", "x", "x" ], [ "x", "dtrill", "o", "o" ], false, 4, 1.5, -1, "f", "f", 325),
new OboeFingering(86, [ 2 ], [ "x", "o", "o" ], [ "x", "dtrill", "o", "o" ], false, 3, 1.5, -1, "p", "f", false),
new OboeFingering(86, [ 2 ], [ "h", "o", "o" ], [ "x", "dtrill", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86, [  ], [ "h", "x", "x" ], [ "o", "x", "h", "c" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86, [  ], [ "h", "x", "x", "bb" ], [ "o", "x", "h", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86, [  ], [ "h", "x", "x", "bb" ], [ "o", "x", "o" ], false, 4, 1.5, 1, "mp", "ff", 176),
new OboeFingering(86, [  ], [ "h", "x", "x" ], [ "o", "o", "x" ], false, 3, 1.5, 1, "pp", "ff", false),
new OboeFingering(86, [  ], [ "h", "x", "x" ], [ "o", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86, [  ], [ "h", "x", "h" ], [ "x", "o", "o" ], false, 3, 1.5, 1, "mf", "f", 191),
new OboeFingering(86, [  ], [ "h", "x", "x" ], [ "x", "dtrill", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86, [  ], [ "o", "x", "x" ], [ "o", "x", "o" ], false, 3, 1.5, 1, "f", "ff", 256),
new OboeFingering(86, [  ], [ "h", "x", "cistrill", "x" ], [ "x", "x", "o", "cis" ], false, 3, 1.5, 1, "mp", "ff", 312),
new OboeFingering(86, [ 2 ], [ "x", "o", "x" ], [ "x", "dtrill", "o", "x" ], false, 3, 1.5, 2, "mp", "ff", false),
new OboeFingering(86, [ 1 ], [ "h", "h", "x", "b" ], [ "o", "x", "o", "eb" ], false, 3, 1.5, 3, "mp", "mf", false),
new OboeFingering(86.5, [ 1 ], [ "h", "x", "x" ], [ "o", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", 179),
new OboeFingering(86.5, [ 1 ], [ "x", "x", "x", "b" ], [ "o", "dtrill", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86.5, [ 1 ], [ "h", "x", "x", "b" ], [ "o", "x", "f", "o", "c" ], false, 3, 1.5, 1, "pp", "ff", 259),
new OboeFingering(86.5, [  ], [ "x", "x", "cistrill", "x" ], [ "o", "x", "x", "c" ], false, 4, 1.5, 1, "mp", "ff", 288),
new OboeFingering(86.5, [  ], [ "x", "x", "cistrill", "x" ], [ "o", "o", "o" ], false, 4, 1.5, 1, "mp", "ff", 295),
new OboeFingering(86.5, [ 2 ], [ "x", "o", "x" ], [ "x", "dtrill", "o", "o" ], false, 3, 1.5, 1, "p", "ff", false),
new OboeFingering(86.5, [  ], [ "h", "x", "x" ], [ "o", "dtrill", "o", "h" ], false, 3, 1.5, 1, "mp", "ff", false),
new OboeFingering(86.5, [  ], [ "h", "x", "x" ], [ "o", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86.5, [  ], [ "h", "x", "x" ], [ "o", "o", "h", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86.5, [  ], [ "h", "x", "x" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86.5, [  ], [ "h", "x", "x" ], [ "o", "o", "h", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86.5, [  ], [ "h", "x", "x" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86.5, [ 2 ], [ "h", "o", "o" ], [ "x", "dtrill", "o", "h" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(86.5, [ 1 ], [ "h", "h", "x" ], [ "o", "x", "f", "o", "c" ], false, 3, 1.5, 2, "pp", "ff", false),
new OboeFingering(87, [  ], [ "x", "x", "x", "b" ], [ "o", "dtrill", "o", "o" ], false, 3, 1.5, -1, "mf", "ff", 329),
new OboeFingering(87, [ 2 ], [ "o", "o", "o" ], [ "x", "dtrill", "o", "o" ], false, 3, 1.5, -1, "mf", "ff", false),
new OboeFingering(87, [  ], [ "h", "x", "x", "bb" ], [ "o", "x", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87, [ 1 ], [ "h", "x", "x", "bb" ], [ "o", "x", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87, [  ], [ "h", "x", "x" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87, [  ], [ "h", "x", "x", "ab" ], [ "o", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87, [  ], [ "o", "x", "x" ], [ "o", "x", "x" ], false, 4, 1.5, 1, "p", "ff", 244),
new OboeFingering(87, [ 2 ], [ "o", "x", "x" ], [ "o", "x", "x" ], false, 5, 1.5, 1, "p", "ff", 246),
new OboeFingering(87, [  ], [ "o", "x", "x", "b" ], [ "o", "x", "x" ], false, 4, 1.5, 1, "f", "ff", 247),
new OboeFingering(87, [ 2 ], [ "x", "x", "cistrill", "x" ], [ "o", "o", "o" ], false, 4, 1.5, 1, "p", "ff", 390),
new OboeFingering(87, [  ], [ "x", "x", "x" ], [ "o", "dtrill", "o", "o", "c" ], false, 4, 1.5, 1, "mp", "ff", 330),
new OboeFingering(87, [ 2 ], [ "o", "x", "x", "bb" ], [ "o", "dtrill", "x", "o" ], false, 3, 1.5, 1, "mp", "mf", false),
new OboeFingering(87, [  ], [ "h", "x", "x" ], [ "o", "x", "h" ], false, 4, 1.5, 2, "mf", "ff", 173),
new OboeFingering(87, [  ], [ "h", "h", "x" ], [ "o", "x", "x", "cis" ], false, 4, 1.5, 2, "f", "ff", 216),
new OboeFingering(87, [  ], [ "x", "x", "cistrill", "h" ], [ "o", "x", "o", "eb" ], false, 4, 1.5, 2, "mf", "ff", 300),
new OboeFingering(87.5, [  ], [ "h", "x", "h" ], [ "o", "dtrill", "o", "o" ], false, 3, 1.5, -1, "mf", "ff", false),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab" ], [ "o", "o", "o", "c" ], false, 3, 1.5, 0, "p", "ff", 180),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab" ], [ "o", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87.5, [ 1 ], [ "h", "x", "x", "f" ], [ "ab", "o", "x", "x", "c" ], false, 3, 1.5, 1, "mp", "f", 168),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab" ], [ "o", "x", "x", "cis" ], false, 3, 1.5, 1, "p", "f", 170),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab" ], [ "o", "x", "o", "cis" ], false, 3, 1.5, 1, "p", "f", 177),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab" ], [ "o", "x", "o", "eb" ], false, 5, 1.5, 1, "f", "ff", false),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 1, "p", "ff", 182),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab" ], [ "o", "o", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87.5, [  ], [ "h", "x", "o", "ab" ], [ "o", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab", "eb" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87.5, [ 1 ], [ "h", "x", "x", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 1, "p", "ff", 182),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "bb" ], [ "o", "x", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(87.5, [  ], [ "h", "x", "h" ], [ "o", "o", "o" ], false, 3, 1.5, 1, "mf", "ff", 195),
new OboeFingering(87.5, [  ], [ "x", "x", "cistrill", "x" ], [ "o", "x", "x", "eb" ], false, 4, 1.5, 1, "mf", "ff", 290),
new OboeFingering(87.5, [  ], [ "x", "x", "cistrill", "x" ], [ "ab", "o", "o", "o" ], false, 5, 1.5, 1, "mf", "ff", 296),
new OboeFingering(87.5, [  ], [ "h", "x", "x", "ab" ], [ "o", "x", "h", "c" ], false, 3, 1.5, 2, "p", "f", 175),
new OboeFingering(87.5, [ 3 ], [ "h", "x", "h" ], [ "o", "x", "x", "cis" ], false, 3, 1.5, 2, "pp", "mf", false),
new OboeFingering(87.5, [ 3 ], [ "h", "x", "h", "bb" ], [ "o", "o", "h", "c" ], false, 1, 1.5, 2, "mp", "mf", false),
new OboeFingering(88, [ 3 ], [ "x", "x", "cistrill", "x" ], [ "ab", "o", "o", "o" ], false, 3, 1.5, -1, "p", "f", 298),
new OboeFingering(88, [ 3 ], [ "h", "x", "x", "ab" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88, [ 3 ], [ "h", "x", "x", "ab" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88, [ 3 ], [ "h", "x", "x", "ab", "eb" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88, [ 3 ], [ "h", "x", "o", "ab", "eb" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88, [ 3 ], [ "h", "x", "x", "ab" ], [ "o", "o", "h", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88, [  ], [ "h", "x", "x", "ab" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88, [ 3 ], [ "h", "x", "cistrill", "x", "ab" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 1, "mf", "ff", 292),
new OboeFingering(88, [ 3 ], [ "x", "x", "cistrill", "x" ], [ "ab", "o", "x", "o", "cis" ], false, 4, 1.5, 1, "mp", "f", 294),
new OboeFingering(88, [  ], [ "h", "x", "cistrill", "x" ], [ "ab", "o", "x", "x", "eb" ], false, 4, 1.5, 1, "f", "ff", 315),
new OboeFingering(88, [  ], [ "x", "x", "o" ], [ "o", "dtrill", "o", "h", "eb" ], false, 3, 1.5, 1, "mf", "ff", false),
new OboeFingering(88.5, [ 3 ], [ "h", "h", "x", "ab" ], [ "o", "o", "x", "cis" ], false, 3, 1.5, -1, "pp", "ff", false),
new OboeFingering(88.5, [ 3 ], [ "h", "o", "x", "ab" ], [ "o", "x", "f", "o", "c" ], false, 3, 1.5, -1, "p", "ff", false),
new OboeFingering(88.5, [ 3 ], [ "x", "x", "cistrill", "h" ], [ "ab", "o", "o", "o" ], false, 4, 1.5, -1, "pp", "ff", 304),
new OboeFingering(88.5, [ 3 ], [ "h", "x", "h", "ab", "eb" ], [ "o", "x", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88.5, [ 3 ], [ "h", "x", "h", "ab", "eb" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88.5, [ 3 ], [ "h", "x", "o" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(88.5, [ 3 ], [ "h", "o", "x", "ab" ], [ "o", "x", "x" ], false, 3, 1.5, 1, "pp", "f", false),
new OboeFingering(88.5, [ 3 ], [ "h", "h", "x", "bb" ], [ "ab", "o", "o", "h", "c" ], false, 3, 1.5, 2, "pp", "ff", false),
new OboeFingering(89, [ 3 ], [ "x", "x", "cistrill", "o", "ab" ], [ "o", "o", "h", "eb" ], false, 3, 1.5, -1, "mp", "mf", 307),
new OboeFingering(89, [ 3 ], [ "h", "x", "o", "ab", "eb" ], [ "o", "x", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(89, [ 3 ], [ "h", "x", "o", "ab", "eb" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(89, [ 3 ], [ "x", "x", "h", "b" ], [ "x", "x", "h", "c" ], false, 5, 2, 1, "mf", "ff", false),
new OboeFingering(89, [ 1 ], [ "h", "x", "o", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 1, "p", "ff", 199),
new OboeFingering(89, [ 3 ], [ "o", "x", "h", "ab", "eb" ], [ "o", "x", "x" ], false, 3, 2, 1, "p", "ff", false),
new OboeFingering(89, [ 3 ], [ "x", "h", "x", "bb" ], [ "ab", "o", "x", "x", "eb" ], false, 3, 1.5, 2, "ppp", "fff", false),
new OboeFingering(89.5, [ 3 ], [ "x", "x", "x" ], [ "x", "x", "x", "cis" ], false, 5, 1.5, -1, "mf", "ff", 4),
new OboeFingering(89.5, [ 3 ], [ "x", "x", "o" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(89.5, [  ], [ "x", "x", "x" ], [ "x", "h", "h", "cis" ], false, 5, 1.5, -1, "ff", "ff", 13),
new OboeFingering(89.5, [ 1 ], [ "x", "x", "h", "b" ], [ "x", "x", "o", "c" ], false, 5, 1.5, -1, "p", "ff", 362),
new OboeFingering(89.5, [ 3 ], [ "h", "h", "h", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, -1, "p", "ff", false),
new OboeFingering(89.5, [ 3 ], [ "h", "h", "o", "ab", "eb" ], [ "o", "x", "x" ], false, 3, 1.5, 0, "mp", "ff", false),
new OboeFingering(89.5, [  ], [ "x", "x", "h", "bb" ], [ "x", "x", "o", "cis" ], false, 4, 1.5, 1, "ff", "ff", 27),
new OboeFingering(89.5, [ 3 ], [ "x", "h", "h", "ab" ], [ "o", "o", "o" ], false, 3, 1.5, 1, "p", "ff", 108),
new OboeFingering(89.5, [ 1 ], [ "x", "x", "h" ], [ "x", "o", "h", "c" ], false, 3, 1.5, 2, "p", "f", false),
new OboeFingering(89.5, [ 3 ], [ "x", "h", "x", "b" ], [ "x", "x", "h", "cis" ], false, 3, 1.5, 2, "mf", "ff", 66),
new OboeFingering(89.5, [ 3 ], [ "x", "h", "x", "b" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 3, "p", "ff", false),
new OboeFingering(89.5, [ 3 ], [ "h", "h", "h", "bb" ], [ "ab", "o", "o", "x", "eb" ], false, 3, 1.5, 3, "mf", "ff", false),
new OboeFingering(89.5, [ 3 ], [ "o", "x", "o", "ab", "eb" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(89.5, [ 3 ], [ "h", "h", "o", "ab", "eb" ], [ "o", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90, [  ], [ "x", "x", "h", "bb" ], [ "x", "x", "f", "o", "eb" ], false, 4, 1.5, -1, "ff", "ff", 28),
new OboeFingering(90, [ 3 ], [ "x", "x", "o" ], [ "x", "x", "x" ], false, 3, 1.5, -1, "p", "ff", 37),
new OboeFingering(90, [ 3 ], [ "x", "x", "o" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, -1, "ppp", "fff", 40),
new OboeFingering(90, [ 3 ], [ "x", "x", "o" ], [ "x", "x", "o", "c" ], false, 3, 1.5, -1, "p", "ff", 48),
new OboeFingering(90, [ 3 ], [ "x", "x", "o" ], [ "x", "o", "o", "c" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90, [ 3 ], [ "x", "x", "o", "bb" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90, [ 3 ], [ "x", "x", "o" ], [ "x", "o", "h", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90, [ 3 ], [ "x", "x", "o", "ab" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90, [ 3 ], [ "x", "x", "o", "b" ], [ "x", "x", "o", "c" ], false, 3, 1.5, 1, "p", "ff", 45),
new OboeFingering(90, [ 3 ], [ "x", "x", "o", "bb" ], [ "x", "x", "o" ], false, 3, 1.5, 2, "p", "ff", 44),
new OboeFingering(90, [ 3 ], [ "h", "o", "o", "ab" ], [ "o", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90, [ 3 ], [ "h", "o", "o", "ab", "eb" ], [ "o", "x", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90.5, [ 3 ], [ "x", "h", "o", "f" ], [ "x", "x", "x", "cis" ], false, 3, 1.5, -1, "mf", "ff", 110),
new OboeFingering(90.5, [ 3 ], [ "x", "h", "o" ], [ "x", "x", "o", "c" ], false, 3, 1.5, -1, "mf", "ff", false),
new OboeFingering(90.5, [ 3 ], [ "h", "x", "o" ], [ "x", "x", "f", "o", "c" ], false, 3, 1.5, -1, "mf", "ff", false),
new OboeFingering(90.5, [ 3 ], [ "x", "h", "o" ], [ "x", "o", "o", "c" ], false, 3, 1.5, 0, "ppp", "fff", 117),
new OboeFingering(90.5, [ 3 ], [ "x", "x", "o" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90.5, [ 3 ], [ "x", "o", "x" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90.5, [ 3 ], [ "x", "h", "o" ], [ "x", "o", "h", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90.5, [ 3 ], [ "x", "h", "o", "bb" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90.5, [ 3 ], [ "o", "x", "o" ], [ "x", "x", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(90.5, [  ], [ "x", "x", "o", "f" ], [ "x", "x", "x" ], false, 5, 1.5, 1, "ff", "ff", 41),
new OboeFingering(90.5, [  ], [ "x", "h", "h", "bb", "f" ], [ "x", "x", "h", "cis" ], false, 5, 1.5, 1, "f", "ff", 95),
new OboeFingering(90.5, [  ], [ "x", "h", "h" ], [ "x", "x", "f", "o", "cis" ], false, 5, 1.5, 1, "ff", "ff", 100),
new OboeFingering(90.5, [  ], [ "x", "h", "h" ], [ "x", "x", "f", "o" ], false, 5, 1.5, 1, "ff", "ff", 101),
new OboeFingering(90.5, [ 3 ], [ "x", "h", "o", "f" ], [ "x", "x", "x" ], false, 3, 1.5, 1, "f", "ff", 111),
new OboeFingering(90.5, [ 1 ], [ "x", "x", "o" ], [ "x", "x", "f", "o", "eb" ], false, 4, 1.5, 2, "mf", "f", 49),
new OboeFingering(91, [ 1 ], [ "x", "h", "o" ], [ "x", "x", "f", "o" ], false, 5, 1.5, -1, "mf", "ff", false),
new OboeFingering(91, [ 3 ], [ "x", "o", "x" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(91, [ 3 ], [ "x", "o", "x", "bb" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(91, [ 3 ], [ "o", "x", "o" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(91, [ 3 ], [ "x", "o", "x" ], [ "x", "o", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(91, [ 1, 3 ], [ "x", "h", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 1, "mp", "ff", 115),
new OboeFingering(91, [ 3 ], [ "x", "h", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 1, "p", "ff", 116),
new OboeFingering(91, [  ], [ "x", "o", "h", "b", "f" ], [ "x", "x", "o", "eb" ], false, 5, 1.5, 1, "f", "ff", 138),
new OboeFingering(91, [  ], [ "x", "o", "h" ], [ "x", "x", "f", "o" ], false, 5, 1.5, 1, "f", "ff", 140),
new OboeFingering(91, [ 1 ], [ "x", "o", "h" ], [ "x", "x", "f", "o" ], false, 5, 1.5, 1, "f", "ff", 141),
new OboeFingering(91, [ 3 ], [ "x", "o", "x" ], [ "x", "o", "x" ], false, 5, 1.5, 2, "mf", "ff", false),
new OboeFingering(91, [ 3 ], [ "x", "o", "h", "f" ], [ "x", "o", "x" ], false, 4, 1.5, 2, "p", "ff", 146),
new OboeFingering(91, [ 3 ], [ "h", "x", "o", "ab", "eb" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(91.5, [ 3 ], [ "h", "o", "o", "ab" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "p", "ff", false),
new OboeFingering(91.5, [ 3 ], [ "h", "o", "o", "ab" ], [ "x", "o", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(91.5, [ 2, 3 ], [ "h", "o", "o", "ab" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(91.5, [ 3 ], [ "h", "h", "o" ], [ "x", "o", "x" ], false, 5, 1.5, 1, "f", "ff", false),
new OboeFingering(91.5, [ 3 ], [ "x", "o", "x", "b" ], [ "x", "x", "x", "c" ], false, 5, 1.5, 2, "mf", "ff", false),
new OboeFingering(91.5, [ 3 ], [ "x", "o", "o" ], [ "x", "o", "x", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(91.5, [ 2, 3 ], [ "x", "o", "x" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92, [ 3 ], [ "x", "o", "o" ], [ "x", "o", "o" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92, [ 3 ], [ "x", "o", "o", "bb" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92, [ 3 ], [ "x", "o", "o" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92, [ 3 ], [ "x", "o", "o" ], [ "x", "x", "f", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92, [ 3 ], [ "x", "o", "o" ], [ "x", "x", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92, [ 1 ], [ "x", "o", "x", "b" ], [ "o", "x", "x" ], false, 5, 1.5, 1, "f", "ff", false),
new OboeFingering(92, [ 1 ], [ "h", "o", "x", "b" ], [ "o", "x", "x", "cis" ], false, 3, 1.5, 2, "mf", "ff", false),
new OboeFingering(92.5, [ 3 ], [ "h", "o", "o" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92.5, [ 3 ], [ "h", "o", "o" ], [ "x", "o", "o", "eb" ], false, 3, 1.5, 0, "p", "ff", false),
new OboeFingering(92.5, [ 3 ], [ "h", "o", "o", "b" ], [ "x", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92.5, [ 3 ], [ "h", "o", "o", "bb" ], [ "x", "o", "o", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92.5, [ 3 ], [ "x", "o", "x" ], [ "o", "x", "x", "eb" ], false, 3, 1.5, 1, "ff", "ff", false),
new OboeFingering(92.5, [ 2, 3 ], [ "x", "o", "o" ], [ "x", "o", "o", "c" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(92.5, [ 2, 3 ], [ "x", "o", "o" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93, [ 2, 3 ], [ "o", "o", "x" ], [ "o", "o", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93, [ 2, 3 ], [ "o", "o", "x", "bb" ], [ "o", "o", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93, [ 2, 3 ], [ "o", "x", "x", "c" ], [ "o", "o", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93, [ 3 ], [ "o", "o", "o" ], [ "x", "o", "o" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93.5, [ 1 ], [ "o", "x", "x", "ab" ], [ "o", "x", "x", "c" ], false, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93.5, [ 2, 3 ], [ "o", "o", "x" ], [ "o", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93.5, [ 2, 3 ], [ "o", "o", "x", "bb" ], [ "o", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93.5, [ 2, 3 ], [ "o", "o", "x", "ab" ], [ "o", "o", "x" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93.5, [ 2, 3 ], [ "o", "o", "x", "ab" ], [ "o", "o", "x", "cis" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(93.5, [ 2, 3 ], [ "o", "o", "x", "ab" ], [ "o", "o", "x", "eb" ], true, 3, 1.5, 0, "ppp", "fff", false),
new OboeFingering(94, [ 2, 3 ], [ "o", "o", "x", "ab" ], [ "o", "o", "x" ], false, 3, 1.5, 0, "ppp", "fff", false),
];
